# COMPOSE_PROJECT_NAME=zk_test
version: '3'
services:
    zoo1:
        image: zookeeper
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 200M
                reservations:
                    cpus: '0.25'
                    memory: 20M
        restart: always
        container_name: zoo1
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: zookeeper
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 200M
                reservations:
                    cpus: '0.25'
                    memory: 20M
        restart: always
        container_name: zoo2
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: zookeeper
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 200M
                reservations:
                    cpus: '0.25'
                    memory: 20M
        restart: always
        container_name: zoo3
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888